name: Build Reductant

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4

      - name: Show Xcode version
        run: xcodebuild -version

      - name: Install ldid
        run: brew install ldid

      - name: Build
        run: bash build.sh

      - name: Upload rt_spawn
        uses: actions/upload-artifact@v4
        with:
          name: rt_spawn
          path: rt_spawn

      - name: Upload rt_hooker
        uses: actions/upload-artifact@v4
        with:
          name: rt_hooker.dylib
          path: rt_hooker.dylib

      - name: Upload arm64_runner
        uses: actions/upload-artifact@v4
        with:
          name: arm64_runner
          path: arm64_runner
